## install brew
# check update, and install brew if it does not exist
- name: update brew
  register: result
  ignore_errors: True
  command: brew update

- name: get brew installer
  get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest=/tmp/brew_install
  when: result|failed

- name: proceed brew installer
  command: >
    ruby /tmp/brew_install
  when: result|failed

# install apps
- name: update homebrew
  homebrew: update_homebrew=yes
  become: False

- name: tap external homebrew repositories
  homebrew_tap: 
    tap: "{{ item.tap }}"
    state: present
  with_items:
    - "{{ repositories }}"
  when: repositories
  become: False

- name: install homebrew cask packages
  homebrew_cask: 
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ cask_packages }}"
  when: cask_packages
  become: False


- name: install and upgrade homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_option | default('') }}"
  with_items:
    - "{{ packages }}"
  when: packages
  become: False

